version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /typescript
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      typescript-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      github-actions:
        patterns:
          - "*"
